[".oh-my-zsh"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
[".oh-my-zsh/custom/themes/powerlevel10k"]
exact = true
stripComponents = 1
type = "archive"
url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
